name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    uses: ArwynFr/ArwynFr/.github/workflows/pwsh-deployment.yaml@main
    with:
      manifest: ./ConventionalVersioning/ConventionalVersioning.psd1
      source: ./ConventionalVersioning/
    secrets:
      PSGALLERY_APIKEY: ${{ secrets.PSGALLERY_APIKEY }}
